# Initialize the graphics environment
options(device = "windows")

# Import data
LungCapData = read.table(file.choose(), header = TRUE, sep = "\t", 
                         stringsAsFactors = TRUE) # Import the data

# Get metadata
head(LungCapData)
names(LungCapData)
class(LungCapData$Gender)
levels(LungCapData$Gender)
class(LungCapData$Smoke)
levels(LungCapData$Smoke)

## MULTIVARIATE REGRESSION

ageheight_vs_lungcap_model = lm(LungCapData$LungCap ~ 
                                  LungCapData$Age + LungCapData$Height)
sprintf("The formula is LUNGCAP = %.3f + %.3f[AGE] + %.3f[HEIGHT]", 
        as.numeric(ageheight_vs_lungcap_model$coefficients[1]),
        as.numeric(ageheight_vs_lungcap_model$coefficients[2]),
        as.numeric(ageheight_vs_lungcap_model$coefficients[3]))

# Get summary information about the analysis
# Note: Intercept is Y value when all explanatory variables are null
summary(ageheight_vs_lungcap_model)
cor(LungCapData$Age, LungCapData$Height)
coef(ageheight_vs_lungcap_model)
confint(ageheight_vs_lungcap_model)


all_vs_lungcap_model = lm(LungCapData$LungCap ~ 
                            LungCapData$Age + 
                            LungCapData$Height +
                            LungCapData$Smoke + 
                            LungCapData$Gender +
                            LungCapData$Caesarean)

# Plot residuals
par(mfrow = c(2,2))
plot(all_vs_lungcap_model)

## Converting numeric variable to categorical variable

# Converting height to A (<50), B=50-55, C=55-6-, D=60-65, E=65-70, F=70+
#  Intervals by default are left-open, right-closed (a, b]
cat_height = cut(LungCapData$Height,
                 breaks = c(0, 50, 55, 60, 65, 70, 100),
                 labels = c("A", "B", "C", "D", "E", "F"))
cat_height = cut(LungCapData$Height,
                 breaks = c(0, 50, 55, 60, 65, 70, 100),
                 labels = c("A", "B", "C", "D", "E", "F"),
                 right = FALSE) # Left closed, right open
cat_height = cut(LungCapData$Height,
                 breaks = 4, # Creates four categories dynamically generated by R
                 right = FALSE) # Left closed, right open

## Dummy / Indicator Variables
# NOTE: Variable with k possible values can have k-1 dummy variables
#  For any observation, each will its dummy variable set to 1 and the rest to 0
#  The coefficient for each level corresponds to change in mean outcome for 
#    change in category variable Xn relative to X0 (reference var)
#  Default reference var R chooses is first alphabetically or numerically
mean(LungCapData$LungCap[cat_height == "A"])
mean(LungCapData$LungCap[cat_height == "B"])
mean(LungCapData$LungCap[cat_height == "C"])
mean(LungCapData$LungCap[cat_height == "D"])
mean(LungCapData$LungCap[cat_height == "E"])
mean(LungCapData$LungCap[cat_height == "F"])
catheight_vs_lungcap_model = lm(LungCapData$LungCap ~ cat_height)

## Changing reference/ baseline variables in regression with R
# In a linear regression model, the intercept refers to the estimated mean 
#   Y-value for the reference (baseline) group, and the model coefficients 
#   (parameters: b) refer to expected changes in the mean Y-value relative 
#   to the reference group for an increase of 1 controlling for other vars
age_smoke_vs_lungcap_model = lm(LungCapData$LungCap ~ 
                                  LungCapData$Age + 
                                  LungCapData$Smoke)

# Adjust the levels such that the reference category is adjusted
LungCapData$Smoke = relevel(LungCapData$Smoke, ref = "yes")

## Create a new linear model with age and smoking as separate lines
releveled_age_smoke_vs_lungcap_model = lm(LungCapData$LungCap ~ 
                                            LungCapData$Age + 
                                            LungCapData$Smoke)
plot(LungCapData$Age[LungCapData$Smoke == "no"],
     LungCapData$LungCap[LungCapData$Smoke == "no"],
     main = "Age / Smoking vs Lung Capacity",
     xlab = "Age",
     ylab = "Lung Capacity",
     las = 1,
     col = "blue")
plot(LungCapData$Age[LungCapData$Smoke == "yes"],
     LungCapData$LungCap[LungCapData$Smoke == "yes"],
     main = "Age / Smoking vs Lung Capacity",
     xlab = "Age",
     ylab = "Lung Capacity",
     las = 1,
     col = "red")
# If two regression lines were to be plotted for each group, they'd have
#   the same slope which implies independence with no interaction / 
#   effect modification